# Generated by Django 5.1.4 on 2025-01-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
